#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

multiping - Plugin to monitor ping times against several hosts

=head1 CONFIGURATION

The following environment variables are used

 ping_args  - Arguments to ping (default "-c 2")
 ping_args2 - Arguments after the host name (required for Solaris)
 ping       - Ping program to use
 host       - Host to ping

Configuration example

 [multiping]
  env.host www.example.org mail.example.org

Configuration example for Solaris

 [multiping]
  env.host www.example.org mail.example.org
  env.ping_args -s
  env.ping_args2 56 2

=head1 AUTHOR

Copyright (C) 2004 Jimmy Olsen

=head1 LICENSE

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; version 2 dated June,
1991.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

=head1 MAGIC MARKERS

 #%# family=manual

=cut

if [ -z "$host" ]; then
    file_host=$(basename $0 | sed 's/^ping_//g')
    host=${host:-${file_host:-www.google.com}}
fi

if [ "$1" = "config" ]; then
    echo multigraph multiping
    echo graph_title Ping times
    echo 'graph_args --base 1000 -l 0'
    echo 'graph_vlabel seconds'
    echo 'graph_category network'
    echo 'graph_info This graph shows ping RTT statistics.'
    for hosts in $host; do
	site=`expr $site + 1`
	echo "site$site.label $hosts"
	echo "site$site.info Ping RTT statistics for $hosts."
	echo "site$site.draw LINE2"
    done
    echo ""
    echo multigraph packetloss
    echo graph_title Packetloss
    echo 'graph_vlabel %'
    echo 'graph_category network'
    echo 'graph_info This graph shows ping packet loss.'
    site=0
    for hosts in $host; do
	site=`expr $site + 1`
	echo "site${site}.label $hosts"
	echo "site${site}.info Ping packet loss statistics for $hosts."
	echo "site${site}.warning 10"
	echo "site${site}.critical 90"
    done
    exit 0
fi

export ping="${ping:-'ping'}"
export ping_args="${ping_args:-'-c 2'}"
export hosts="${host}"
export ping_args2="${ping_args2}"


perl -e '
    @hosts = split(/ /, $ENV{'hosts'});
    $ping = $ENV{'ping'};
    $ping_args = $ENV{'ping_args'};
    $ping_arg2 = $ENV{'ping_arg2'};
    $site=1;
    foreach $host (@hosts) {
	$_ = qx{$ping $ping_args $host $ping_args2 2>/dev/null};
        $latency{$site} = $1 / 1000 if m@min/avg/max.*\s\d+(?:\.\d+)?/(\d+(?:\.\d+)?)/\d+(?:\.\d+)?@;
        $pl{$site} = $1 if /(\d+)% packet loss/;
	$site++;
    }
    print "multigraph multiping\n";
    foreach $key (sort {$a <=> $b} keys %latency) {
	print "site${key}.value $latency{$key}\n";
    }
    print "\nmultigraph packetloss\n";
    foreach $key (sort {$a <=> $b} keys %pl) {
	print "site${key}.value $pl{$key}\n";
    }
'
